### ISSUE TITLE
We have a cert problem. The internet is gross.

### ISSUE THREAD

**Issue by flyinprogrammer** [remh/docker-dd-agent-build-rpm-x64#1]
We use this container to build our internal dd-agent so we can test it before contributing upstream PRs. We noticed this when building yesterday:

``` bash
[Builder: xproto] I | Writing license file from http://cgit.freedesktop.org/xorg/proto/xproto/plain/COPYING to /opt/datadog-agent/licenses/xproto/COPYING
[08:54:06][Step 1/1]                   [Builder: xproto] I | Adding License: 'http://cgit.freedesktop.org/xorg/proto/xproto/plain/COPYING': 0.4542s
[08:54:06][Step 1/1] /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/openssl/ssl.rb:232:in `post_connection_check': hostname "cgit.freedesktop.org" does not match the server certificate (OpenSSL::SSL::SSLError)
[08:54:06][Step 1/1]    from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:925:in `connect'
[08:54:06][Step 1/1]                   [Builder: xproto] I | Build xproto: 0.455s
[08:54:06][Step 1/1]    from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
[08:54:06][Step 1/1]    from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:852:in `start'
[08:54:06][Step 1/1]    from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1375:in `request'
[08:54:06][Step 1/1]    from /usr/local/rvm/gems/ruby-2.2.2/gems/httparty-0.13.7/lib/httparty/request.rb:117:in `perform'
[08:54:06][Step 1/1]    from /usr/local/rvm/gems/ruby-2.2.2/gems/httparty-0.13.7/lib/httparty/request.rb:291:in `handle_response'
[08:54:06][Step 1/1]    from /usr/local/rvm/gems/ruby-2.2.2/gems/httparty-0.13.7/lib/httparty/request.rb:131:in `perform'
[08:54:06][Step 1/1]    from /usr/local/rvm/gems/ruby-2.2.2/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
[08:54:06][Step 1/1]    from /usr/local/rvm/gems/ruby-2.2.2/gems/httparty-0.13.7/lib/httparty.rb:476:in `get'
[08:54:06][Step 1/1]    from /usr/local/rvm/gems/ruby-2.2.2/gems/httparty-0.13.7/lib/httparty.rb:583:in `get'
```

cgit.freedesktop.org relies on SNI. SNI isn't supported in openssl until [OpenSSL 0.9.8f](https://wiki.apache.org/httpd/NameBasedSSLVHostsWithSNI) 

``` bash
openssl version
OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008
```

Idk how you want to go about upgrading openssl on centos 5... it's all gross.

**Comment by remh** [comment]
@flyinprogrammer yeah you're right :/

We are hitting the same issue actually, we have a PR open on the main Datadog repo for that:
https://github.com/DataDog/docker-dd-agent-build-rpm-x64/pull/5

Wanna give it a try ? I'm going to close this repo soon as it's not maintained (the maintained one is the one owned by DataDog).

**Comment by flyinprogrammer** [comment]
Oh hey I'll close this - thank you for your work on this!!! you're an amazing human!
